"""
Module centralisant tous les états de conversation utilisés dans le bot Telegram.
"""

# États de la conversation
(
    MAIN_MENU,
    POST_CONTENT,
    POST_ACTIONS,
    SEND_OPTIONS,
    AUTO_DESTRUCTION,
    SCHEDULE_SEND,
    EDIT_POST,
    SCHEDULE_SELECT_CHANNEL,
    STATS_SELECT_CHANNEL,
    WAITING_CHANNEL_INFO,
    SETTINGS,
    BACKUP_MENU,
    WAITING_CHANNEL_SELECTION,
    WAITING_PUBLICATION_CONTENT,
    WAITING_TIMEZONE,
    WAITING_THUMBNAIL,
    WAITING_REACTION_INPUT,
    WAITING_URL_INPUT,
    WAITING_RENAME_INPUT,
    WAITING_SCHEDULE_TIME,
    WAITING_EDIT_TIME,
    WAITING_CUSTOM_USERNAME
) = range(22)  # 22 états au total 