# Constantes pour les états de conversation du bot

# États principaux
MAIN_MENU = 0
CREATE_PUBLICATION = 1
PLANIFIER_POST = 2
SETTINGS = 3

# États d'attente d'entrée utilisateur
WAITING_TEXT = 4
WAITING_MEDIA = 5
WAITING_SCHEDULE_TEXT = 6
WAITING_SCHEDULE_MEDIA = 7
WAITING_TIMEZONE = 8
WAITING_NEW_TIME = 9

# États de sélection et d'action
SCHEDULE_SELECT_CHANNEL = 10
SCHEDULE_SEND = 11
WAITING_CHANNEL = 12
WAITING_POST_CONTENT = 13
WAITING_POST_ACTIONS = 14

# État de sélection de canal
WAITING_CHANNEL_SELECTION = 15
WAITING_PUBLICATION_CONTENT = 16
POST_ACTIONS = 17
SEND_OPTIONS = 18
AUTO_DESTRUCTION = 19
EDIT_POST = 20
STATS_SELECT_CHANNEL = 21
WAITING_CHANNEL_INFO = 22
BACKUP_MENU = 23

# États de la conversation
WAITING_SCHEDULE_TIME = 17
WAITING_EDIT_TIME = 20
WAITING_CANCEL_CONFIRMATION = 21
WAITING_PREVIEW = 22
WAITING_TIMEZONE_SETUP = 24
WAITING_NEW_TIMEZONE = 25 